# Generated by Django 4.2.4 on 2023-12-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='дизлайк')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.publication', verbose_name='запись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто дизлайкнул')),
            ],
            options={
                'verbose_name': 'дизлайк',
                'verbose_name_plural': 'дизлайки',
            },
        ),
    ]
