# Generated by Django 4.2.4 on 2023-12-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.AddField(
            model_name='publication',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='платная публикация'),
        ),
    ]
