# Generated by Django 4.2.4 on 2024-01-02 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
